export const confluxConstants = {
    CONNECT_SUCCESS: 'CONNECT_SUCCESS',
    CONNECT_LOADING: 'CONNECTING',
    CONNECT_FAILED: 'CONNECT_FAILED',
    CONNECT_NOT_ALLOWED: 'CONNECT_NOT_ALLOWED',
    CONNECT_ALLOWED: 'CONNECT_ALLOWED'
}
  